import { Router, type IRouter } from "express";
import healthRouter from "./health";
import postersRouter from "./posters";
import posterSizesRouter from "./posterSizes";
import cartRouter from "./cart";
import favoritesRouter from "./favorites";
import ordersRouter from "./orders";
import newsletterRouter from "./newsletter";
import statsRouter from "./stats";
import mockupsRouter from "./mockups";
import storesRouter from "./stores";
import authRouter from "./auth";
import adminAuthRouter from "./adminAuth";
import shippingRouter from "./shipping";
import launchChecklistRouter from "./launchChecklist";
import stripeRouter from "./stripe";
import contentPagesRouter from "./contentPages";
import storageRouter from "./storage";
import analyzePlacementRouter from "./analyzePlacement";
import mockupSyncRouter from "./mockupSync";
import generateMockupTemplateRouter from "./generateMockupTemplate";

const router: IRouter = Router();

router.use(adminAuthRouter);
router.use(authRouter);
router.use(healthRouter);
router.use(postersRouter);
router.use(posterSizesRouter);
router.use(cartRouter);
router.use(favoritesRouter);
router.use(ordersRouter);
router.use(newsletterRouter);
router.use(statsRouter);
router.use(mockupsRouter);
router.use(storesRouter);
router.use(shippingRouter);
router.use(launchChecklistRouter);
router.use(stripeRouter);
router.use(contentPagesRouter);
router.use(storageRouter);
router.use(analyzePlacementRouter);
router.use(mockupSyncRouter);
router.use(generateMockupTemplateRouter);

export default router;
